# Generated by Django 3.0.5 on 2020-06-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_auto_20200622_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
